# Generated by Django 5.0.4 on 2024-04-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('mode_of_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('message', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
